name: release
on:
 push:
  branches:
   - main
  tags:
   - 'v*.*.*'
env:
 GOLANG_VERSION: "1.18.x"
jobs:
 goreleaser:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v4
     with:
      fetch-depth: 1

   - name: Setup Go
     uses: actions/setup-go@v4
     with:
      go-version: ${{env.GOLANG_VERSION}}

   - name: Run Tests
     run: go test ./... -v

   - name: Run GoReleaser
     if: startsWith(github.ref, 'refs/tags/')
     uses: goreleaser/goreleaser-action@v5
     with:
      version: latest
      args: release --clean
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

