name: release
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
env:
  GOLANG_VERSION: "1.21.x"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{env.GOLANG_VERSION}}

      - name: Run Tests
        run: make test

      - name: Run GoReleaser
        if: startsWith(github.ref, 'refs/tags/')
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/dcm:${GITHUB_REF#refs/tags/}
          IMAGE_NAME_LATEST=ghcr.io/${{ github.repository }}/dcm:latest
          docker build -t $IMAGE_NAME -t $IMAGE_NAME_LATEST .
          docker push $IMAGE_NAME
          docker push $IMAGE_NAME_LATEST
