name: release
on:
 push:
  branches:
   - main
  tags:
   - 'v*.*.*'
env:
 GOLANG_VERSION: "1.18.x"
jobs:
 goreleaser:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v2
     with:
      fetch-depth: 1

   - name: Setup Go
     uses: actions/setup-go@v2
     with:
      go-version: ${{env.GOLANG_VERSION}}

   - name: Run GoReleaser
     uses: goreleaser/goreleaser-action@v2
     with:
      version: latest
      args: release --rm-dist
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

